#!/usr/bin/env python3
"""go_hb.py — manifest for the Go Engineering Handbook (zariya.in).

This handbook uses `preserve_markdown`: the rich, multi-section content for each
topic lives in go/markdown/<slug>.md (authored directly / via the generation
workflow). This file only declares the manifest (metadata) used to build
data.js, the category dashboard, search, and the portal card. The `overview`
field is a fallback stub used by hb_lib only if a markdown file is missing.

Each topic page follows a 15-section template:
  1 Overview · 2 Why It Exists · 3 Internal Working · 4 Syntax ·
  5 Common Interview Questions · 6 Production Use Cases · 7 Common Mistakes ·
  8 Performance Considerations · 9 Best Practices · 10 Code Examples ·
  11 Advanced Concepts · 12 Debugging Tips · 13 Senior Engineer Notes ·
  14 Staff Engineer Notes · 15 Revision Summary
Interview pages are Q&A banks; case studies use an architecture-first template.
"""

# (name, level, icon)
CATEGORIES = [
    ("Go Fundamentals",       "Beginner",     "📘"),
    ("Concurrency",           "Intermediate", "🔀"),
    ("Memory & Performance",  "Advanced",     "⚡"),
    ("Backend Engineering",   "Intermediate", "🌐"),
    ("Advanced Go",           "Advanced",     "🧩"),
    ("Production Engineering", "Advanced",     "🚀"),
    ("Interview Mastery",     "Intermediate", "🎯"),
    ("Case Studies",          "Advanced",     "🏗️"),
]

# (slug, name, category, level, summary, [keywords], [refs])
TOPICS = [
    # ---------------- Section A: Go Fundamentals (1-30) ----------------
    ("01-introduction-to-go", "Introduction to Go", "Go Fundamentals", "Beginner",
     "What Go is, why Google built it, and where it dominates today.",
     ["go", "golang", "compiled", "static typing", "garbage collected"], ["A Tour of Go", "go.dev"]),
    ("02-go-philosophy", "Go Philosophy", "Go Fundamentals", "Beginner",
     "Simplicity, readability, composition over inheritance, and orthogonality.",
     ["simplicity", "readability", "composition", "proverbs", "gofmt"], ["Go Proverbs", "Effective Go"]),
    ("03-go-toolchain", "Go Toolchain", "Go Fundamentals", "Beginner",
     "go build, run, test, vet, mod, and the single-binary compile model.",
     ["go build", "go test", "go vet", "go mod", "toolchain"], ["go command docs"]),
    ("04-project-structure", "Project Structure", "Go Fundamentals", "Beginner",
     "Idiomatic layout: cmd, internal, pkg, modules, and import paths.",
     ["project layout", "internal", "cmd", "go modules", "monorepo"], ["golang-standards/project-layout"]),
    ("05-packages", "Packages", "Go Fundamentals", "Beginner",
     "Compilation units, exported identifiers, init order, and import cycles.",
     ["package", "import", "exported", "init", "import cycle"], ["Effective Go: Packages"]),
    ("06-variables", "Variables", "Go Fundamentals", "Beginner",
     "var, short declaration, zero values, scoping, and shadowing.",
     ["var", ":=", "zero value", "scope", "shadowing"], ["A Tour of Go"]),
    ("07-constants", "Constants", "Go Fundamentals", "Beginner",
     "Typed/untyped constants, iota, and compile-time evaluation.",
     ["const", "iota", "untyped constant", "enum", "compile-time"], ["Go blog: Constants"]),
    ("08-data-types", "Data Types", "Go Fundamentals", "Beginner",
     "Numeric, string, bool, and composite types with memory sizes.",
     ["int", "string", "rune", "byte", "float"], ["A Tour of Go"]),
    ("09-type-conversion", "Type Conversion", "Go Fundamentals", "Beginner",
     "Explicit conversions, no implicit coercion, and numeric pitfalls.",
     ["conversion", "cast", "strconv", "overflow", "rune byte"], ["Go spec: Conversions"]),
    ("10-operators", "Operators", "Go Fundamentals", "Beginner",
     "Arithmetic, bitwise, comparison, and the absence of operator overloading.",
     ["operators", "bitwise", "precedence", "comparison", "shift"], ["Go spec: Operators"]),
    ("11-control-flow", "Control Flow", "Go Fundamentals", "Beginner",
     "if, for (the only loop), switch, labels, goto, and fallthrough.",
     ["if", "for", "switch", "label", "fallthrough"], ["A Tour of Go"]),
    ("12-functions", "Functions", "Go Fundamentals", "Beginner",
     "First-class functions, signatures, and value-vs-reference arguments.",
     ["func", "first-class", "signature", "pass by value", "recursion"], ["Effective Go"]),
    ("13-multiple-return-values", "Multiple Return Values", "Go Fundamentals", "Beginner",
     "The (result, err) idiom and tuple-like returns without tuples.",
     ["multiple return", "comma ok", "result err", "tuple", "blank identifier"], ["Effective Go"]),
    ("14-named-returns", "Named Returns", "Go Fundamentals", "Beginner",
     "Named result parameters, naked returns, and defer interaction.",
     ["named return", "naked return", "defer", "result params", "readability"], ["Go spec"]),
    ("15-variadic-functions", "Variadic Functions", "Go Fundamentals", "Beginner",
     "Variadic params, slice spreading, and append internals.",
     ["variadic", "...", "spread", "append", "slice"], ["Effective Go"]),
    ("16-closures", "Closures", "Go Fundamentals", "Intermediate",
     "Functions capturing variables by reference and the loop-var trap.",
     ["closure", "capture", "loop variable", "scope", "go 1.22"], ["Go blog: Closures"]),
    ("17-pointers", "Pointers", "Go Fundamentals", "Beginner",
     "Address-of, dereference, nil pointers, and no pointer arithmetic.",
     ["pointer", "*", "&", "nil", "dereference"], ["A Tour of Go"]),
    ("18-arrays", "Arrays", "Go Fundamentals", "Beginner",
     "Fixed-size value types, copy semantics, and when to use them.",
     ["array", "fixed size", "value type", "copy", "len"], ["Go blog: Arrays"]),
    ("19-slices", "Slices", "Go Fundamentals", "Intermediate",
     "The slice header, len/cap, append growth, and aliasing bugs.",
     ["slice", "len cap", "append", "backing array", "aliasing"], ["Go blog: Slices"]),
    ("20-maps", "Maps", "Go Fundamentals", "Intermediate",
     "Hash maps, iteration order, comma-ok, and concurrency safety.",
     ["map", "hash", "comma ok", "delete", "concurrent map"], ["Go blog: Maps"]),
    ("21-structs", "Structs", "Go Fundamentals", "Beginner",
     "Value composition, embedding, tags, and memory alignment.",
     ["struct", "embedding", "tags", "alignment", "composite literal"], ["Effective Go"]),
    ("22-methods", "Methods", "Go Fundamentals", "Beginner",
     "Method sets, pointer vs value receivers, and method expressions.",
     ["method", "receiver", "pointer receiver", "method set", "method value"], ["Effective Go"]),
    ("23-interfaces", "Interfaces", "Go Fundamentals", "Intermediate",
     "Implicit satisfaction, the iface/eface pair, and accept-interfaces.",
     ["interface", "implicit", "iface", "nil interface", "duck typing"], ["Effective Go: Interfaces"]),
    ("24-type-assertions", "Type Assertions", "Go Fundamentals", "Intermediate",
     "Recovering dynamic types safely with the comma-ok form.",
     ["type assertion", "comma ok", "panic", "interface", "dynamic type"], ["Go spec"]),
    ("25-type-switches", "Type Switches", "Go Fundamentals", "Intermediate",
     "Dispatching on dynamic type and idiomatic error inspection.",
     ["type switch", "case", "interface", "dispatch", "any"], ["Go spec"]),
    ("26-generics", "Generics", "Go Fundamentals", "Advanced",
     "Type parameters, constraints, inference, and the GC shape stencil.",
     ["generics", "type parameters", "constraints", "comparable", "inference"], ["Go generics tutorial"]),
    ("27-error-handling", "Error Handling", "Go Fundamentals", "Intermediate",
     "Errors as values, wrapping with %w, errors.Is/As, sentinels.",
     ["error", "errors.Is", "errors.As", "%w", "sentinel"], ["Go blog: Error handling"]),
    ("28-panic-and-recover", "Panic and Recover", "Go Fundamentals", "Intermediate",
     "When panics happen, recover boundaries, and not using them as exceptions.",
     ["panic", "recover", "defer", "stack unwind", "goroutine crash"], ["Go blog: Defer Panic Recover"]),
    ("29-defer", "Defer", "Go Fundamentals", "Beginner",
     "LIFO deferred calls, argument capture timing, and cleanup patterns.",
     ["defer", "LIFO", "cleanup", "named return", "loop defer"], ["Go blog: Defer Panic Recover"]),
    ("30-reflection", "Reflection", "Go Fundamentals", "Advanced",
     "reflect.Type/Value, the laws of reflection, and its performance cost.",
     ["reflection", "reflect", "Type Value", "tags", "interface"], ["Go blog: Laws of Reflection"]),

    # ---------------- Section B: Concurrency (31-48) ----------------
    ("31-goroutines", "Goroutines", "Concurrency", "Intermediate",
     "Lightweight green threads, growable stacks, and M:N scheduling.",
     ["goroutine", "go keyword", "stack", "scheduler", "leak"], ["Go blog: Concurrency"]),
    ("32-channels", "Channels", "Concurrency", "Intermediate",
     "Typed conduits, send/receive semantics, close, and nil channels.",
     ["channel", "send receive", "close", "nil channel", "hchan"], ["Go blog: Share memory by communicating"]),
    ("33-buffered-channels", "Buffered Channels", "Concurrency", "Intermediate",
     "Capacity, async sends, and back-pressure via bounded buffers.",
     ["buffered channel", "capacity", "back-pressure", "ring buffer", "blocking"], ["Go spec: Channels"]),
    ("34-select-statement", "Select Statement", "Concurrency", "Intermediate",
     "Multiplexing channels, default, timeouts, and pseudo-random choice.",
     ["select", "default", "timeout", "multiplex", "done channel"], ["Go spec: Select"]),
    ("35-worker-pools", "Worker Pools", "Concurrency", "Intermediate",
     "Bounding concurrency with a fixed set of workers over a job channel.",
     ["worker pool", "bounded concurrency", "job queue", "semaphore", "throughput"], ["Concurrency patterns"]),
    ("36-fan-out-fan-in", "Fan-Out Fan-In", "Concurrency", "Intermediate",
     "Distributing work to many goroutines and merging their results.",
     ["fan-out", "fan-in", "merge", "pipeline", "parallelism"], ["Go blog: Pipelines"]),
    ("37-pipelines", "Pipelines", "Concurrency", "Advanced",
     "Composable channel stages with cancellation and clean shutdown.",
     ["pipeline", "stage", "done channel", "cancellation", "streaming"], ["Go blog: Pipelines"]),
    ("38-mutex", "Mutex", "Concurrency", "Intermediate",
     "sync.Mutex internals, starvation mode, and lock-ordering discipline.",
     ["mutex", "lock", "critical section", "starvation", "contention"], ["sync package"]),
    ("39-rwmutex", "RWMutex", "Concurrency", "Intermediate",
     "Read-write locks, when they help, and reader-writer starvation.",
     ["rwmutex", "read lock", "write lock", "contention", "readers"], ["sync package"]),
    ("40-waitgroup", "WaitGroup", "Concurrency", "Intermediate",
     "Counting goroutine completion and the Add-before-launch rule.",
     ["waitgroup", "Add Done Wait", "counter", "barrier", "reuse"], ["sync package"]),
    ("41-atomic-operations", "Atomic Operations", "Concurrency", "Advanced",
     "Lock-free counters, atomic.Value, CAS, and the typed atomics.",
     ["atomic", "CAS", "load store", "lock-free", "atomic.Value"], ["sync/atomic"]),
    ("42-context-package", "Context Package", "Concurrency", "Advanced",
     "Propagating cancellation, deadlines, and request-scoped values.",
     ["context", "cancel", "deadline", "timeout", "values"], ["Go blog: Context"]),
    ("43-cancellation-patterns", "Cancellation Patterns", "Concurrency", "Advanced",
     "Done channels, context trees, and graceful shutdown of fan-outs.",
     ["cancellation", "graceful shutdown", "done", "errgroup", "context"], ["Go blog: Pipelines"]),
    ("44-deadlocks", "Deadlocks", "Concurrency", "Advanced",
     "The four conditions, all-goroutines-asleep, and detection.",
     ["deadlock", "lock ordering", "circular wait", "detector", "blocking"], ["Go runtime"]),
    ("45-race-conditions", "Race Conditions", "Concurrency", "Advanced",
     "Data races, the -race detector, and happens-before guarantees.",
     ["race condition", "data race", "-race", "happens-before", "tsan"], ["Go blog: Race detector"]),
    ("46-scheduler-internals", "Scheduler Internals", "Concurrency", "Advanced",
     "Work-stealing, run queues, preemption, and syscall handoff.",
     ["scheduler", "work stealing", "run queue", "preemption", "netpoller"], ["Go scheduler design"]),
    ("47-gmp-model", "GMP Model", "Concurrency", "Advanced",
     "Goroutines (G), machines (M), processors (P), and GOMAXPROCS.",
     ["GMP", "G M P", "GOMAXPROCS", "local queue", "global queue"], ["Go scheduler design doc"]),
    ("48-memory-model", "Memory Model", "Concurrency", "Advanced",
     "Happens-before, synchronization edges, and what is guaranteed.",
     ["memory model", "happens-before", "visibility", "synchronization", "reordering"], ["The Go Memory Model"]),

    # ---------------- Section C: Memory & Performance (49-60) ----------------
    ("49-escape-analysis", "Escape Analysis", "Memory & Performance", "Advanced",
     "How the compiler decides stack vs heap and reading -gcflags=-m.",
     ["escape analysis", "stack heap", "gcflags -m", "inlining", "allocation"], ["Go compiler docs"]),
    ("50-heap-vs-stack", "Heap vs Stack", "Memory & Performance", "Advanced",
     "Per-goroutine stacks, growable frames, and heap allocation costs.",
     ["stack", "heap", "growable stack", "allocation", "escape"], ["Go runtime"]),
    ("51-garbage-collector", "Garbage Collector", "Memory & Performance", "Advanced",
     "Concurrent tri-color mark-sweep, GC pacing, and GOGC/GOMEMLIMIT.",
     ["garbage collector", "tri-color", "mark sweep", "GOGC", "GOMEMLIMIT"], ["Go GC guide"]),
    ("52-memory-allocation", "Memory Allocation", "Memory & Performance", "Advanced",
     "mcache/mcentral/mheap, size classes, and tiny allocator.",
     ["allocator", "mcache", "size class", "mheap", "span"], ["Go runtime: malloc"]),
    ("53-memory-leaks", "Memory Leaks", "Memory & Performance", "Advanced",
     "Goroutine leaks, slice retention, and growing maps in Go.",
     ["memory leak", "goroutine leak", "slice retention", "map growth", "pprof"], ["pprof docs"]),
    ("54-profiling", "Profiling", "Memory & Performance", "Advanced",
     "CPU, heap, block, and mutex profiles and how to read them.",
     ["profiling", "cpu profile", "heap profile", "block", "mutex profile"], ["Go blog: Profiling"]),
    ("55-benchmarking", "Benchmarking", "Memory & Performance", "Advanced",
     "testing.B, b.N, allocs/op, benchstat, and avoiding micro-bench traps.",
     ["benchmark", "testing.B", "benchstat", "allocs/op", "ResetTimer"], ["Go testing docs"]),
    ("56-pprof", "pprof", "Memory & Performance", "Advanced",
     "net/http/pprof, flame graphs, and live production diagnosis.",
     ["pprof", "flame graph", "net/http/pprof", "profile", "trace"], ["pprof docs"]),
    ("57-cpu-optimization", "CPU Optimization", "Memory & Performance", "Advanced",
     "Hot paths, inlining, bounds-check elimination, and cache locality.",
     ["cpu optimization", "inlining", "bounds check", "cache", "hot path"], ["Go performance"]),
    ("58-memory-optimization", "Memory Optimization", "Memory & Performance", "Advanced",
     "Struct layout, field ordering, and shrinking working sets.",
     ["memory optimization", "struct layout", "padding", "alignment", "working set"], ["Go performance"]),
    ("59-allocation-reduction", "Allocation Reduction", "Memory & Performance", "Advanced",
     "sync.Pool, preallocation, byte buffers, and zero-allocation APIs.",
     ["allocation reduction", "sync.Pool", "preallocate", "zero alloc", "reuse"], ["sync.Pool docs"]),
    ("60-high-throughput-systems", "High Throughput Systems", "Memory & Performance", "Advanced",
     "Designing for millions of ops/sec: batching, sharding, and back-pressure.",
     ["high throughput", "batching", "sharding", "back-pressure", "latency"], ["Production engineering"]),

    # ---------------- Section D: Backend Engineering (61-80) ----------------
    ("61-http-package", "HTTP Package", "Backend Engineering", "Intermediate",
     "net/http server model, Handler interface, and ServeMux internals.",
     ["net/http", "Handler", "ServeMux", "Server", "ResponseWriter"], ["net/http docs"]),
    ("62-rest-apis", "REST APIs", "Backend Engineering", "Intermediate",
     "Resource design, routing, status codes, and versioning in Go.",
     ["REST", "routing", "status codes", "versioning", "chi"], ["REST best practices"]),
    ("63-middleware", "Middleware", "Backend Engineering", "Intermediate",
     "Handler-wrapping chains for logging, auth, recovery, and tracing.",
     ["middleware", "handler chain", "decorator", "recovery", "logging"], ["chi", "net/http"]),
    ("64-json-handling", "JSON Handling", "Backend Engineering", "Intermediate",
     "encoding/json, struct tags, streaming, and custom marshalers.",
     ["json", "Marshal", "Unmarshal", "struct tags", "json.Decoder"], ["encoding/json docs"]),
    ("65-validation", "Validation", "Backend Engineering", "Intermediate",
     "Request validation strategies, go-playground/validator, and errors.",
     ["validation", "validator", "struct tags", "request binding", "errors"], ["go-playground/validator"]),
    ("66-dependency-injection", "Dependency Injection", "Backend Engineering", "Intermediate",
     "Constructor injection, wiring without frameworks, and testability.",
     ["dependency injection", "constructor", "wire", "interfaces", "testability"], ["google/wire"]),
    ("67-configuration-management", "Configuration Management", "Backend Engineering", "Intermediate",
     "Env vars, flags, files, 12-factor config, and viper.",
     ["config", "env vars", "viper", "12-factor", "flags"], ["12factor.net"]),
    ("68-logging", "Logging", "Backend Engineering", "Intermediate",
     "Log levels, the log package, and choosing a logging strategy.",
     ["logging", "log levels", "stdout", "log package", "rotation"], ["log/slog"]),
    ("69-structured-logging", "Structured Logging", "Backend Engineering", "Intermediate",
     "log/slog, JSON logs, correlation IDs, and log-based observability.",
     ["structured logging", "slog", "json logs", "correlation id", "zap"], ["log/slog docs"]),
    ("70-authentication", "Authentication", "Backend Engineering", "Intermediate",
     "Sessions vs tokens, password hashing, and auth middleware.",
     ["authentication", "session", "bcrypt", "oauth", "middleware"], ["OWASP"]),
    ("71-jwt", "JWT", "Backend Engineering", "Intermediate",
     "JWT structure, signing, validation, refresh tokens, and pitfalls.",
     ["jwt", "claims", "signing", "refresh token", "HS256 RS256"], ["jwt.io"]),
    ("72-rbac", "RBAC", "Backend Engineering", "Advanced",
     "Role-based access control, policy models, and Casbin in Go.",
     ["rbac", "authorization", "roles", "policy", "casbin"], ["casbin.org"]),
    ("73-rate-limiting", "Rate Limiting", "Backend Engineering", "Advanced",
     "Token bucket, leaky bucket, golang.org/x/time/rate, and distributed limits.",
     ["rate limiting", "token bucket", "leaky bucket", "x/time/rate", "redis"], ["x/time/rate"]),
    ("74-caching", "Caching", "Backend Engineering", "Intermediate",
     "Cache patterns, eviction, in-process LRU, and invalidation.",
     ["caching", "LRU", "TTL", "cache-aside", "invalidation"], ["Caching patterns"]),
    ("75-redis-integration", "Redis Integration", "Backend Engineering", "Intermediate",
     "go-redis, pipelining, pub/sub, distributed locks, and patterns.",
     ["redis", "go-redis", "pipelining", "pub/sub", "distributed lock"], ["go-redis docs"]),
    ("76-postgresql-integration", "PostgreSQL Integration", "Backend Engineering", "Intermediate",
     "database/sql, pgx, connection pools, and prepared statements.",
     ["postgresql", "database/sql", "pgx", "connection pool", "prepared statement"], ["pgx docs"]),
    ("77-database-transactions", "Database Transactions", "Backend Engineering", "Advanced",
     "ACID, isolation levels, retries, and the unit-of-work pattern.",
     ["transactions", "ACID", "isolation level", "deadlock retry", "unit of work"], ["PostgreSQL docs"]),
    ("78-repository-pattern", "Repository Pattern", "Backend Engineering", "Intermediate",
     "Abstracting persistence behind interfaces for testability.",
     ["repository pattern", "interface", "persistence", "mock", "domain"], ["DDD"]),
    ("79-clean-architecture", "Clean Architecture", "Backend Engineering", "Advanced",
     "Layered dependencies, the dependency rule, and use-case isolation.",
     ["clean architecture", "dependency rule", "use case", "layers", "ports"], ["Clean Architecture"]),
    ("80-hexagonal-architecture", "Hexagonal Architecture", "Backend Engineering", "Advanced",
     "Ports and adapters, driving vs driven sides, and testing the core.",
     ["hexagonal", "ports adapters", "driving", "driven", "domain core"], ["Alistair Cockburn"]),

    # ---------------- Section E: Advanced Go (81-96) ----------------
    ("81-design-patterns-in-go", "Design Patterns in Go", "Advanced Go", "Advanced",
     "Idiomatic Go takes on classic GoF patterns and when to skip them.",
     ["design patterns", "GoF", "idiomatic", "strategy", "factory"], ["GoF", "Effective Go"]),
    ("82-functional-options-pattern", "Functional Options Pattern", "Advanced Go", "Advanced",
     "Extensible constructors via variadic option functions.",
     ["functional options", "variadic", "constructor", "config", "API design"], ["Dave Cheney"]),
    ("83-builder-pattern", "Builder Pattern", "Advanced Go", "Intermediate",
     "Fluent construction of complex objects and when options beat builders.",
     ["builder pattern", "fluent", "construction", "chaining", "config"], ["GoF"]),
    ("84-dependency-injection-patterns", "Dependency Injection Patterns", "Advanced Go", "Advanced",
     "Manual wiring, wire codegen, and DI at scale without magic.",
     ["dependency injection", "wire", "fx", "wiring", "container"], ["google/wire", "uber-go/fx"]),
    ("85-event-driven-architecture", "Event Driven Architecture", "Advanced Go", "Advanced",
     "Events, async messaging, eventual consistency, and the outbox.",
     ["event driven", "async", "outbox", "eventual consistency", "pub/sub"], ["EDA patterns"]),
    ("86-message-queues", "Message Queues", "Advanced Go", "Advanced",
     "Delivery guarantees, idempotency, DLQs, and broker choices.",
     ["message queue", "at-least-once", "idempotency", "DLQ", "broker"], ["Messaging patterns"]),
    ("87-kafka-with-go", "Kafka with Go", "Advanced Go", "Advanced",
     "Producers, consumer groups, partitions, offsets, and franz-go/sarama.",
     ["kafka", "consumer group", "partition", "offset", "sarama franz-go"], ["Kafka docs"]),
    ("88-grpc", "gRPC", "Advanced Go", "Advanced",
     "RPC over HTTP/2, streaming, interceptors, and deadlines.",
     ["grpc", "http2", "streaming", "interceptor", "deadline"], ["grpc.io"]),
    ("89-protocol-buffers", "Protocol Buffers", "Advanced Go", "Advanced",
     "Schema-first serialization, wire format, and backward compatibility.",
     ["protobuf", "proto3", "wire format", "schema evolution", "codegen"], ["protobuf docs"]),
    ("90-websockets", "WebSockets", "Advanced Go", "Advanced",
     "Persistent bidirectional connections, gorilla/coder ws, and scaling.",
     ["websocket", "bidirectional", "upgrade", "gorilla", "fan-out"], ["RFC 6455"]),
    ("91-microservices", "Microservices", "Advanced Go", "Advanced",
     "Service boundaries, communication, and the operational tax.",
     ["microservices", "boundaries", "communication", "saga", "monolith"], ["microservices.io"]),
    ("92-service-discovery", "Service Discovery", "Advanced Go", "Advanced",
     "Registries, DNS, client vs server-side LB, and health checks.",
     ["service discovery", "consul", "dns", "load balancing", "health check"], ["Consul docs"]),
    ("93-distributed-tracing", "Distributed Tracing", "Advanced Go", "Advanced",
     "Spans, trace context propagation, and end-to-end latency analysis.",
     ["distributed tracing", "span", "trace context", "jaeger", "propagation"], ["W3C Trace Context"]),
    ("94-opentelemetry", "OpenTelemetry", "Advanced Go", "Advanced",
     "Unified traces/metrics/logs, the SDK, exporters, and the collector.",
     ["opentelemetry", "otel", "exporter", "collector", "instrumentation"], ["opentelemetry.io"]),
    ("95-circuit-breakers", "Circuit Breakers", "Advanced Go", "Advanced",
     "Failing fast, half-open probing, and cascading-failure prevention.",
     ["circuit breaker", "half-open", "fail fast", "gobreaker", "cascading failure"], ["Release It!"]),
    ("96-resilience-patterns", "Resilience Patterns", "Advanced Go", "Advanced",
     "Retries, backoff, timeouts, bulkheads, and graceful degradation.",
     ["resilience", "retry", "backoff", "bulkhead", "timeout"], ["Release It!"]),

    # ---------------- Section F: Production Engineering (97-110) ----------------
    ("97-testing", "Testing", "Production Engineering", "Intermediate",
     "The testing package, the test pyramid, and Go's testing philosophy.",
     ["testing", "go test", "test pyramid", "coverage", "fixtures"], ["Go testing docs"]),
    ("98-unit-testing", "Unit Testing", "Production Engineering", "Intermediate",
     "Fast isolated tests, t.Helper, subtests, and assertions.",
     ["unit testing", "t.Run", "t.Helper", "testify", "subtests"], ["Go testing docs"]),
    ("99-table-driven-tests", "Table Driven Tests", "Production Engineering", "Intermediate",
     "The idiomatic Go test pattern with cases, subtests, and t.Parallel.",
     ["table driven", "test cases", "subtests", "t.Parallel", "golden"], ["Go wiki: TableDrivenTests"]),
    ("100-integration-testing", "Integration Testing", "Production Engineering", "Advanced",
     "Testing against real dependencies with testcontainers and build tags.",
     ["integration testing", "testcontainers", "build tags", "docker", "ci"], ["testcontainers-go"]),
    ("101-mocking", "Mocking", "Production Engineering", "Intermediate",
     "Interface-based mocks, fakes vs mocks, gomock, and over-mocking.",
     ["mocking", "gomock", "fakes", "interfaces", "stub"], ["gomock docs"]),
    ("102-benchmark-testing", "Benchmark Testing", "Production Engineering", "Advanced",
     "Writing reliable benchmarks and comparing with benchstat.",
     ["benchmark", "testing.B", "benchstat", "allocs/op", "regression"], ["Go testing docs"]),
    ("103-dockerizing-go-apps", "Dockerizing Go Apps", "Production Engineering", "Intermediate",
     "Multi-stage builds, distroless/scratch images, and tiny binaries.",
     ["docker", "multi-stage", "distroless", "scratch", "static binary"], ["Docker docs"]),
    ("104-kubernetes-deployment", "Kubernetes Deployment", "Production Engineering", "Advanced",
     "Probes, resource limits, graceful shutdown, and 12-factor on k8s.",
     ["kubernetes", "probes", "resource limits", "graceful shutdown", "SIGTERM"], ["Kubernetes docs"]),
    ("105-cicd-pipelines", "CI/CD Pipelines", "Production Engineering", "Intermediate",
     "Building, testing, linting, and releasing Go with GitHub Actions.",
     ["ci/cd", "github actions", "golangci-lint", "goreleaser", "pipeline"], ["GitHub Actions"]),
    ("106-observability", "Observability", "Production Engineering", "Advanced",
     "The three pillars, SLIs/SLOs, and instrumenting Go services.",
     ["observability", "metrics logs traces", "SLO", "SLI", "instrumentation"], ["Google SRE book"]),
    ("107-metrics", "Metrics", "Production Engineering", "Advanced",
     "Counters, gauges, histograms, RED/USE methods, and cardinality.",
     ["metrics", "counter gauge histogram", "RED", "USE", "cardinality"], ["Prometheus docs"]),
    ("108-prometheus", "Prometheus", "Production Engineering", "Advanced",
     "client_golang, exposition format, scraping, and PromQL basics.",
     ["prometheus", "client_golang", "exposition", "scrape", "promql"], ["Prometheus docs"]),
    ("109-grafana", "Grafana", "Production Engineering", "Intermediate",
     "Dashboards, alerts, and visualizing Go service health.",
     ["grafana", "dashboard", "alerting", "panels", "visualization"], ["Grafana docs"]),
    ("110-production-debugging", "Production Debugging", "Production Engineering", "Advanced",
     "Live pprof, goroutine dumps, core dumps, and delve in prod.",
     ["production debugging", "pprof", "goroutine dump", "delve", "core dump"], ["Go diagnostics"]),

    # ---------------- Section G: Interview Mastery (111-119) ----------------
    ("111-interview-beginner-questions", "Beginner Interview Questions", "Interview Mastery", "Beginner",
     "Core syntax, types, slices, maps, and basics — answered and explained.",
     ["interview", "beginner", "basics", "slices", "maps"], ["Interview prep"]),
    ("112-interview-intermediate-questions", "Intermediate Interview Questions", "Interview Mastery", "Intermediate",
     "Interfaces, errors, goroutines, and idioms with follow-ups.",
     ["interview", "intermediate", "interfaces", "errors", "goroutines"], ["Interview prep"]),
    ("113-interview-senior-questions", "Senior Engineer Interview Questions", "Interview Mastery", "Advanced",
     "Design trade-offs, concurrency design, and production judgement.",
     ["interview", "senior", "trade-offs", "design", "concurrency"], ["Interview prep"]),
    ("114-interview-staff-questions", "Staff Engineer Interview Questions", "Interview Mastery", "Advanced",
     "Architecture, scaling, org-level technical leadership questions.",
     ["interview", "staff", "architecture", "scaling", "leadership"], ["Interview prep"]),
    ("115-interview-concurrency-questions", "Concurrency Interview Questions", "Interview Mastery", "Advanced",
     "Channels, the scheduler, races, and concurrency patterns.",
     ["interview", "concurrency", "channels", "scheduler", "race"], ["Interview prep"]),
    ("116-interview-memory-questions", "Memory Interview Questions", "Interview Mastery", "Advanced",
     "GC, escape analysis, stack/heap, and leak diagnosis.",
     ["interview", "memory", "gc", "escape analysis", "leak"], ["Interview prep"]),
    ("117-interview-performance-questions", "Performance Interview Questions", "Interview Mastery", "Advanced",
     "Profiling, benchmarking, and optimization reasoning.",
     ["interview", "performance", "profiling", "benchmark", "optimization"], ["Interview prep"]),
    ("118-interview-system-design-questions", "System Design Interview Questions", "Interview Mastery", "Advanced",
     "Designing scalable systems in Go with concrete trade-offs.",
     ["interview", "system design", "scalability", "trade-offs", "go"], ["Interview prep"]),
    ("119-interview-coding-questions", "Coding Interview Questions", "Interview Mastery", "Intermediate",
     "Hands-on Go coding problems with idiomatic solutions.",
     ["interview", "coding", "algorithms", "go", "problems"], ["Interview prep"]),

    # ---------------- Section H: Case Studies (120-129) ----------------
    ("120-case-study-url-shortener", "Case Study: URL Shortener", "Case Studies", "Advanced",
     "Designing and building a scalable URL shortener in Go.",
     ["url shortener", "base62", "hashing", "redis", "scaling"], ["System design"]),
    ("121-case-study-job-queue", "Case Study: Job Queue", "Case Studies", "Advanced",
     "A durable, retrying background job queue with workers in Go.",
     ["job queue", "workers", "retry", "durability", "redis"], ["System design"]),
    ("122-case-study-cache-layer", "Case Study: Cache Layer", "Case Studies", "Advanced",
     "A multi-tier cache with TTLs, invalidation, and stampede control.",
     ["cache layer", "lru", "ttl", "stampede", "invalidation"], ["System design"]),
    ("123-case-study-rate-limiter", "Case Study: Rate Limiter", "Case Studies", "Advanced",
     "A distributed rate limiter with token buckets backed by Redis.",
     ["rate limiter", "token bucket", "redis", "distributed", "sliding window"], ["System design"]),
    ("124-case-study-chat-server", "Case Study: Chat Server", "Case Studies", "Advanced",
     "A real-time WebSocket chat server with rooms and fan-out.",
     ["chat server", "websocket", "hub", "fan-out", "presence"], ["System design"]),
    ("125-case-study-notification-service", "Case Study: Notification Service", "Case Studies", "Advanced",
     "A multi-channel notification service with queues and retries.",
     ["notification service", "queue", "channels", "retry", "templating"], ["System design"]),
    ("126-case-study-search-service", "Case Study: Search Service", "Case Studies", "Advanced",
     "An inverted-index search service with ranking and pagination.",
     ["search service", "inverted index", "ranking", "elasticsearch", "pagination"], ["System design"]),
    ("127-case-study-api-gateway", "Case Study: API Gateway", "Case Studies", "Advanced",
     "An API gateway with routing, auth, rate limiting, and proxying.",
     ["api gateway", "reverse proxy", "routing", "auth", "rate limiting"], ["System design"]),
    ("128-case-study-distributed-worker-system", "Case Study: Distributed Worker System", "Case Studies", "Advanced",
     "A horizontally scaled worker system with coordination and leasing.",
     ["distributed workers", "coordination", "leasing", "sharding", "scaling"], ["System design"]),
    ("129-case-study-high-throughput-event-processor", "Case Study: High Throughput Event Processor", "Case Studies", "Advanced",
     "A pipeline processing millions of events/sec with batching and back-pressure.",
     ["event processor", "high throughput", "batching", "back-pressure", "kafka"], ["System design"]),
]

SPEC = {
    "id": "go",
    "name": "Go Engineering Handbook",
    "icon": "🐹",
    "tagline": ("Master Go for production systems and FAANG interviews — fundamentals, "
                "concurrency, memory & performance, backend engineering, advanced patterns, "
                "production operations, interview banks, and real case studies."),
    "itemNoun": "Topic",
    "preserve_markdown": True,
    "levels": ["Beginner", "Intermediate", "Advanced"],
    "categories": [{"name": n, "level": lv, "icon": ic} for (n, lv, ic) in CATEGORIES],
    "items": [
        {
            "id": i + 1,
            "slug": slug,
            "name": name,
            "category": cat,
            "level": level,
            "summary": summary,
            "keywords": keywords,
            "refs": refs,
            "overview": summary,  # fallback stub only if markdown file is missing
        }
        for i, (slug, name, cat, level, summary, keywords, refs) in enumerate(TOPICS)
    ],
}
