# SQL Handbook spec — AUTO-GENERATED from topics manifest.
# Rich per-topic markdown lives in sql/markdown/<slug>.md and is preserved
# verbatim by hb_lib.build() (preserve_markdown=True).
SPEC = {'id': 'sql',
 'name': 'SQL Handbook',
 'icon': '🗄️',
 'tagline': 'Beginner → Senior. Master relational databases for interviews and production: queries, joins, window '
            'functions, indexing, query plans, transactions, schema design, and classic interview problems — with '
            'diagrams and a listen mode.',
 'itemNoun': 'Topic',
 'levels': ['Beginner', 'Intermediate', 'Advanced'],
 'categories': [{'name': 'Fundamentals', 'level': 'Beginner', 'icon': '📘'},
                {'name': 'Joins & Aggregation', 'level': 'Beginner', 'icon': '🔗'},
                {'name': 'Advanced Queries', 'level': 'Intermediate', 'icon': '🧩'},
                {'name': 'Performance', 'level': 'Intermediate', 'icon': '⚡'},
                {'name': 'Transactions & Design', 'level': 'Advanced', 'icon': '🏛️'},
                {'name': 'Interview Problems', 'level': 'Advanced', 'icon': '🎯'}],
 'preserve_markdown': True,
 'extraNav': [{'href': 'journey.html', 'label': '🗓️ 30-Day Journey'},
              {'href': 'interview.html', 'label': '🎤 Interview Mode'},
              {'href': 'review.html', 'label': '🔁 Review'}],
 'items': [{'id': 1,
            'slug': '01-select-basics',
            'name': 'SELECT, WHERE, ORDER BY & LIMIT',
            'category': 'Fundamentals',
            'level': 'Beginner',
            'summary': 'Retrieve, filter, sort and limit rows — the foundation of every query.',
            'keywords': ['select', 'where', 'order by', 'limit', 'distinct'],
            'refs': ['PostgreSQL docs: SELECT']},
           {'id': 2,
            'slug': '02-filtering',
            'name': 'Filtering: IN, BETWEEN, LIKE & NULL Logic',
            'category': 'Fundamentals',
            'level': 'Beginner',
            'summary': 'Express precise predicates and handle three-valued (NULL) logic correctly.',
            'keywords': ['where', 'in', 'between', 'like', 'null', 'and or not'],
            'refs': ['PostgreSQL docs: Functions']},
           {'id': 3,
            'slug': '03-sorting-pagination',
            'name': 'Sorting & Pagination',
            'category': 'Fundamentals',
            'level': 'Beginner',
            'summary': 'Deterministic ordering and scalable pagination with keyset vs OFFSET.',
            'keywords': ['order by', 'limit', 'offset', 'keyset', 'seek', 'pagination'],
            'refs': ['Use The Index, Luke: Paging']},
           {'id': 4,
            'slug': '04-data-types',
            'name': 'Data Types, Casting & Basic Constraints',
            'category': 'Fundamentals',
            'level': 'Beginner',
            'summary': 'Pick the right column types and cast safely; NOT NULL/DEFAULT/CHECK basics.',
            'keywords': ['data types', 'cast', 'numeric', 'varchar', 'timestamp', 'default'],
            'refs': ['PostgreSQL docs: Data Types']},
           {'id': 5,
            'slug': '05-joins',
            'name': 'Joins: INNER, LEFT, RIGHT, FULL, CROSS',
            'category': 'Joins & Aggregation',
            'level': 'Beginner',
            'summary': 'Combine rows across tables on a related key.',
            'keywords': ['join', 'inner', 'left', 'full', 'cross', 'on'],
            'refs': ['Use The Index, Luke']},
           {'id': 6,
            'slug': '06-advanced-joins',
            'name': 'Self-Joins, Anti-Joins & Semi-Joins',
            'category': 'Joins & Aggregation',
            'level': 'Intermediate',
            'summary': "Compare rows within a table and express 'has no match' / 'has a match'.",
            'keywords': ['self join', 'anti join', 'semi join', 'exists', 'not exists', 'using'],
            'refs': ['Use The Index, Luke']},
           {'id': 7,
            'slug': '07-group-by',
            'name': 'GROUP BY & Aggregate Functions',
            'category': 'Joins & Aggregation',
            'level': 'Beginner',
            'summary': 'Collapse rows into groups and compute COUNT/SUM/AVG/MIN/MAX.',
            'keywords': ['group by', 'count', 'sum', 'avg', 'aggregate', 'distinct'],
            'refs': ['PostgreSQL docs: Aggregates']},
           {'id': 8,
            'slug': '08-having-grouping-sets',
            'name': 'HAVING, ROLLUP, CUBE & GROUPING SETS',
            'category': 'Joins & Aggregation',
            'level': 'Intermediate',
            'summary': 'Filter groups and produce subtotals/grand totals in one pass.',
            'keywords': ['having', 'rollup', 'cube', 'grouping sets', 'subtotal'],
            'refs': ['PostgreSQL docs: GROUPING SETS']},
           {'id': 9,
            'slug': '09-set-operations',
            'name': 'UNION, INTERSECT & EXCEPT',
            'category': 'Joins & Aggregation',
            'level': 'Intermediate',
            'summary': 'Combine result sets vertically with set semantics.',
            'keywords': ['union', 'union all', 'intersect', 'except', 'set operations'],
            'refs': ['PostgreSQL docs: Combining Queries']},
           {'id': 10,
            'slug': '10-subqueries',
            'name': 'Subqueries: Scalar, Correlated, IN/EXISTS',
            'category': 'Advanced Queries',
            'level': 'Intermediate',
            'summary': 'Nest queries as values, sets, or per-row correlated lookups.',
            'keywords': ['subquery', 'correlated', 'exists', 'in', 'scalar', 'derived table'],
            'refs': ['PostgreSQL docs: Subqueries']},
           {'id': 11,
            'slug': '11-cte',
            'name': 'Common Table Expressions (WITH)',
            'category': 'Advanced Queries',
            'level': 'Intermediate',
            'summary': 'Name and compose query steps for readable, modular SQL.',
            'keywords': ['cte', 'with', 'materialized', 'modular', 'subquery'],
            'refs': ['PostgreSQL docs: WITH']},
           {'id': 12,
            'slug': '12-recursive-cte',
            'name': 'Recursive CTEs',
            'category': 'Advanced Queries',
            'level': 'Advanced',
            'summary': 'Traverse hierarchies and graphs (org charts, trees, paths) in pure SQL.',
            'keywords': ['recursive cte', 'hierarchy', 'tree', 'graph', 'traversal'],
            'refs': ['PostgreSQL docs: Recursive Queries']},
           {'id': 13,
            'slug': '13-window-functions',
            'name': 'Window Functions Fundamentals',
            'category': 'Advanced Queries',
            'level': 'Intermediate',
            'summary': 'Compute across a set of rows without collapsing them (OVER, PARTITION BY).',
            'keywords': ['window function', 'over', 'partition by', 'analytic'],
            'refs': ['PostgreSQL docs: Window Functions']},
           {'id': 14,
            'slug': '14-ranking-window-frames',
            'name': 'Ranking & Window Frames',
            'category': 'Advanced Queries',
            'level': 'Advanced',
            'summary': 'ROW_NUMBER/RANK/DENSE_RANK, LAG/LEAD, running totals and moving windows.',
            'keywords': ['row_number', 'rank', 'dense_rank', 'lag', 'lead', 'frame', 'running total'],
            'refs': ['PostgreSQL docs: Window Functions']},
           {'id': 15,
            'slug': '15-conditional-logic',
            'name': 'CASE, COALESCE & NULLIF',
            'category': 'Advanced Queries',
            'level': 'Beginner',
            'summary': 'Branch, default and guard against NULL inside queries.',
            'keywords': ['case', 'coalesce', 'nullif', 'conditional', 'null handling'],
            'refs': ['PostgreSQL docs: Conditional Expressions']},
           {'id': 16,
            'slug': '16-pivoting',
            'name': 'Pivoting & Conditional Aggregation',
            'category': 'Advanced Queries',
            'level': 'Intermediate',
            'summary': 'Turn rows into columns (and back) with conditional SUM/CASE and crosstab.',
            'keywords': ['pivot', 'unpivot', 'crosstab', 'conditional aggregation', 'case sum'],
            'refs': ['PostgreSQL docs: tablefunc']},
           {'id': 17,
            'slug': '17-string-pattern',
            'name': 'String Functions & Pattern Matching',
            'category': 'Advanced Queries',
            'level': 'Intermediate',
            'summary': 'Manipulate and match text: LIKE, regex, split, concat, trim.',
            'keywords': ['string', 'like', 'regex', 'ilike', 'substring', 'concat', 'split'],
            'refs': ['PostgreSQL docs: String Functions']},
           {'id': 18,
            'slug': '18-date-time',
            'name': 'Date/Time Functions & Intervals',
            'category': 'Advanced Queries',
            'level': 'Intermediate',
            'summary': 'Work with timestamps, intervals, time zones, truncation and bucketing.',
            'keywords': ['date', 'timestamp', 'interval', 'date_trunc', 'extract', 'timezone'],
            'refs': ['PostgreSQL docs: Date/Time']},
           {'id': 19,
            'slug': '19-indexes',
            'name': 'Indexes: B-Tree, Composite & Covering',
            'category': 'Performance',
            'level': 'Intermediate',
            'summary': 'How indexes turn O(n) scans into O(log n) seeks — and their write cost.',
            'keywords': ['index', 'b-tree', 'composite', 'covering', 'clustered', 'secondary'],
            'refs': ['Use The Index, Luke']},
           {'id': 20,
            'slug': '20-index-design',
            'name': 'Index Design & Sargability',
            'category': 'Performance',
            'level': 'Advanced',
            'summary': 'Choose column order, avoid non-sargable predicates, and read the plan.',
            'keywords': ['sargable', 'index design', 'column order', 'selectivity', 'functional index'],
            'refs': ['Use The Index, Luke']},
           {'id': 21,
            'slug': '21-query-optimization',
            'name': 'Query Optimization & EXPLAIN',
            'category': 'Performance',
            'level': 'Advanced',
            'summary': 'Read EXPLAIN/ANALYZE plans and fix the real bottleneck.',
            'keywords': ['explain', 'analyze', 'query plan', 'cost', 'optimizer', 'statistics'],
            'refs': ['PostgreSQL docs: EXPLAIN']},
           {'id': 22,
            'slug': '22-execution-plans',
            'name': 'Execution: Nested Loop, Hash & Merge Joins',
            'category': 'Performance',
            'level': 'Advanced',
            'summary': 'The three physical join algorithms and when the optimizer picks each.',
            'keywords': ['nested loop', 'hash join', 'merge join', 'execution', 'cardinality'],
            'refs': ['PostgreSQL docs: Planner']},
           {'id': 23,
            'slug': '23-partitioning',
            'name': 'Partitioning & Sharding',
            'category': 'Performance',
            'level': 'Advanced',
            'summary': 'Split big tables by range/list/hash for pruning and manageability.',
            'keywords': ['partitioning', 'range', 'hash', 'sharding', 'pruning', 'scale'],
            'refs': ['PostgreSQL docs: Partitioning']},
           {'id': 24,
            'slug': '24-json-semistructured',
            'name': 'JSON & Semi-Structured Data',
            'category': 'Performance',
            'level': 'Intermediate',
            'summary': 'Store, query and index JSON without abandoning relational strengths.',
            'keywords': ['json', 'jsonb', 'gin index', 'semi-structured', '->>', 'containment'],
            'refs': ['PostgreSQL docs: JSON Types']},
           {'id': 25,
            'slug': '25-transactions-acid',
            'name': 'Transactions & ACID',
            'category': 'Transactions & Design',
            'level': 'Intermediate',
            'summary': 'Group statements into atomic, consistent, isolated, durable units.',
            'keywords': ['transaction', 'acid', 'commit', 'rollback', 'atomicity', 'durability'],
            'refs': ['PostgreSQL docs: Transactions']},
           {'id': 26,
            'slug': '26-isolation-levels',
            'name': 'Isolation Levels & Concurrency Anomalies',
            'category': 'Transactions & Design',
            'level': 'Advanced',
            'summary': 'Dirty/non-repeatable/phantom reads and the levels that prevent them.',
            'keywords': ['isolation', 'read committed', 'repeatable read', 'serializable', 'phantom', 'anomaly'],
            'refs': ['DDIA ch.7', 'PostgreSQL docs: Isolation']},
           {'id': 27,
            'slug': '27-locking-mvcc',
            'name': 'Locking, MVCC & Deadlocks',
            'category': 'Transactions & Design',
            'level': 'Advanced',
            'summary': 'How rows are versioned and locked, and how to avoid deadlocks.',
            'keywords': ['mvcc', 'lock', 'deadlock', 'row lock', 'select for update', 'vacuum'],
            'refs': ['PostgreSQL docs: MVCC']},
           {'id': 28,
            'slug': '28-normalization',
            'name': 'Normalization (1NF–BCNF) & Denormalization',
            'category': 'Transactions & Design',
            'level': 'Intermediate',
            'summary': 'Remove redundancy with normal forms — and when to break them on purpose.',
            'keywords': ['normalization', '1nf', '2nf', '3nf', 'bcnf', 'denormalization', 'functional dependency'],
            'refs': ['Database Design textbooks']},
           {'id': 29,
            'slug': '29-keys-constraints',
            'name': 'Keys, Constraints & Referential Integrity',
            'category': 'Transactions & Design',
            'level': 'Beginner',
            'summary': 'Primary/foreign/unique keys and constraints that keep data valid.',
            'keywords': ['primary key', 'foreign key', 'unique', 'check', 'referential integrity', 'cascade'],
            'refs': ['PostgreSQL docs: Constraints']},
           {'id': 30,
            'slug': '30-schema-design',
            'name': 'Schema Design & Data Modeling',
            'category': 'Transactions & Design',
            'level': 'Advanced',
            'summary': 'Model entities, relationships and access patterns into a sound schema.',
            'keywords': ['schema design', 'data modeling', 'er', 'cardinality', 'surrogate key', 'access patterns'],
            'refs': ['The Data Warehouse Toolkit']},
           {'id': 31,
            'slug': '31-views',
            'name': 'Views & Materialized Views',
            'category': 'Transactions & Design',
            'level': 'Intermediate',
            'summary': 'Encapsulate queries as virtual tables; cache expensive ones with matviews.',
            'keywords': ['view', 'materialized view', 'refresh', 'abstraction', 'updatable view'],
            'refs': ['PostgreSQL docs: Views']},
           {'id': 32,
            'slug': '32-procedures-triggers',
            'name': 'Stored Procedures, Functions & Triggers',
            'category': 'Transactions & Design',
            'level': 'Advanced',
            'summary': 'Push logic into the database with routines and event-driven triggers.',
            'keywords': ['stored procedure', 'function', 'trigger', 'plpgsql', 'before after', 'audit'],
            'refs': ['PostgreSQL docs: PL/pgSQL']},
           {'id': 33,
            'slug': '33-problem-nth-highest',
            'name': 'Problem: Nth-Highest Salary',
            'category': 'Interview Problems',
            'level': 'Intermediate',
            'summary': 'The classic ranking problem — with ties, gaps and the N parameter.',
            'keywords': ['nth highest', 'dense_rank', 'limit offset', 'ties', 'ranking problem'],
            'refs': ['LeetCode 177']},
           {'id': 34,
            'slug': '34-problem-top-n-per-group',
            'name': 'Problem: Top-N Per Group',
            'category': 'Interview Problems',
            'level': 'Advanced',
            'summary': 'Highest-paid employee per department — window vs lateral vs correlated.',
            'keywords': ['top n per group', 'partition by', 'lateral', 'greatest-n-per-group', 'window'],
            'refs': ['Use The Index, Luke']},
           {'id': 35,
            'slug': '35-problem-running-total',
            'name': 'Problem: Running Totals & Moving Averages',
            'category': 'Interview Problems',
            'level': 'Advanced',
            'summary': 'Cumulative sums and sliding windows with frame clauses.',
            'keywords': ['running total', 'cumulative', 'moving average', 'window frame', 'rows between'],
            'refs': ['PostgreSQL docs: Window Frames']},
           {'id': 36,
            'slug': '36-problem-gaps-islands',
            'name': 'Problem: Gaps & Islands / Streaks',
            'category': 'Interview Problems',
            'level': 'Advanced',
            'summary': 'Detect consecutive runs and missing sequences with the row-number trick.',
            'keywords': ['gaps and islands', 'streak', 'consecutive', 'row_number diff', 'grouping'],
            'refs': ['SQL Cookbook']}]}
