#!/usr/bin/env python3
"""hb_pipeline.py — generic handbook pipeline driven by a topics JSON."""
import json, os, re, sys
import xml.dom.minidom as minidom

ROOT = "/Users/himanshu/Temp11/DSA-Patterns-Handbook"
SHELL_SRC = os.path.join(ROOT, "numpy-pandas")


def load(path):
    d = json.load(open(path, encoding="utf-8"))
    d.setdefault("module", d["id"].replace("-", "_") + "_hb")
    return d


def cmd_spec(d):
    md_dir = os.path.join(ROOT, d["id"], "markdown")
    items, skipped = [], []
    for it in d["items"]:
        if not os.path.exists(os.path.join(md_dir, it["slug"] + ".md")):
            skipped.append(it["slug"]); continue
        items.append({k: it[k] for k in
                      ("id", "slug", "name", "category", "level", "summary", "keywords", "refs")})
    spec = {
        "id": d["id"], "name": d["name"], "icon": d["icon"], "tagline": d["tagline"],
        "itemNoun": d.get("itemNoun", "Topic"), "videoTag": d.get("videoTag", d["name"]),
        "levels": d["levels"], "categories": d["categories"],
        "preserve_markdown": True,
        "extraNav": [{"href": "journey.html", "label": "🗓️ 30-Day Journey"},
                     {"href": "interview.html", "label": "🎤 Interview Mode"},
                     {"href": "review.html", "label": "🔁 Review"}],
        "items": items,
    }
    out = os.path.join(ROOT, "tools", "src", d["module"] + ".py")
    import pprint
    hdr = ("# %s spec — AUTO-GENERATED by scratchpad/hb_pipeline.py\n"
           "# Source of truth: scratchpad/%s_topics.json. Edit that + author markdown, then regenerate.\n"
           "SPEC = " % (d["name"], d["id"].replace("-", "_")))
    open(out, "w", encoding="utf-8").write(hdr + pprint.pformat(spec, width=120, sort_dicts=False) + "\n")
    print("wrote", out)
    print("included %d chapters; skipped %d: %s" % (len(items), len(skipped), ", ".join(skipped) or "none"))


HB_RE = re.compile(r"<script>window\.HB_JOURNEY=.*?;</script>", re.S)


def cmd_pages(d):
    dst = os.path.join(ROOT, d["id"])
    os.makedirs(dst, exist_ok=True)
    n = len(d["items"])
    cfg = dict(d.get("journey", {}))
    cfg["phases"] = d["phases"]
    hb_line = "<script>window.HB_JOURNEY=" + json.dumps(cfg, ensure_ascii=False) + ";</script>"
    short = re.sub(r"\s*Handbook$", "", d["name"])
    for fname in ("journey.html", "interview.html", "review.html"):
        s = open(os.path.join(SHELL_SRC, fname), encoding="utf-8").read()
        s = HB_RE.sub(lambda _: hb_line, s)
        s = s.replace("NumPy & Pandas Handbook", d["name"]).replace("NumPy & Pandas", short)
        s = s.replace(
            "Mock System Design interviews: rapid-fire question drills with hints, model answers and follow-ups, plus structured design rounds",
            "Mock %s interviews: rapid-fire question drills with hints, model answers and follow-ups, plus design rounds" % short)
        if fname == "journey.html":
            s = s.replace("All 31 topics distributed", "All %d chapters distributed" % n)
            s = re.sub(r'\["Finished all \d+ topics", st\.completed>=\d+\]',
                       '["Finished all %d chapters", st.completed>=%d]' % (n, n), s)
            s = re.sub(r'\["Completed 25 topics", st\.completed>=25\]',
                       '["Completed %d chapters", st.completed>=%d]' % (n // 2, n // 2), s)
        open(os.path.join(dst, fname), "w", encoding="utf-8").write(s)
        print("wrote", os.path.join(dst, fname))


REQUIRED_H2 = ["## 1. Overview", "## 2. Core Concepts", "## 3. Theory", "## 4. Architecture",
               "## 5. Implementation", "## 6. Advantages", "## 7. Common Mistakes",
               "## 8. Production", "## 9. Interview Questions", "## 10. Quick Revision",
               "## 11. Hands-On Exercises", "## 12. Related Topics"]
SVG_RE = re.compile(r"```svg\s*(.*?)```", re.S)


def cmd_gate(d):
    md_dir = os.path.join(ROOT, d["id"], "markdown")
    rows, fails = [], []
    for it in d["items"]:
        nn = "%02d" % it["id"]; p = os.path.join(md_dir, it["slug"] + ".md")
        if not os.path.exists(p):
            fails.append((it["slug"], "MISSING FILE")); continue
        t = open(p, encoding="utf-8").read()
        lines = t.count("\n") + 1
        miss = [h for h in REQUIRED_H2 if h not in t]
        svgs = SVG_RE.findall(t); bad = 0
        for s in svgs:
            try: minidom.parseString(s.strip())
            except Exception: bad += 1
        q = len(re.findall(r"\*\*Q:", t)); sen = len(re.findall(r"\(Senior\)", t))
        probs = []
        if lines < 150: probs.append("short(%d)" % lines)
        if miss: probs.append("missingH2:%d" % len(miss))
        if len(svgs) < 2: probs.append("svg<2(%d)" % len(svgs))
        if bad: probs.append("badSVG:%d" % bad)
        if q < 8: probs.append("Q<8(%d)" % q)
        if not t.lstrip().startswith("# %s ·" % nn): probs.append("H1")
        if ("chapter %s." % nn) not in t: probs.append("footer")
        rows.append((nn, lines, len(svgs), q, sen, "OK" if not probs else ",".join(probs)))
        if probs: fails.append((it["slug"], ",".join(probs)))
    print("%-4s %-6s %-5s %-5s %-7s %s" % ("NN", "lines", "svg", "Q", "senior", "status"))
    for r in rows: print("%-4s %-6d %-5d %-5d %-7d %s" % r)
    print("\nchapters: %d/%d" % (len(rows), len(d["items"])))
    if fails:
        print("FAILURES (%d):" % len(fails))
        for s, p in fails: print("  ", s, "->", p)
        sys.exit(1)
    print("ALL PASS ✅")


if __name__ == "__main__":
    cmd, path = sys.argv[1], sys.argv[2]
    d = load(path)
    {"spec": cmd_spec, "pages": cmd_pages, "gate": cmd_gate}[cmd](d)
